let Gameboard = require('../gameboard');
let Ship = require('../ship');
describe('gameboard', () => {
  it('creates a gameboard', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    expect(newGameboard.board.length).toEqual(10);
    expect(newGameboard.board[0].length).toEqual(10);
    expect(newGameboard.board[0][0]).toBeDefined();
    expect(newGameboard.board[10]).toBeUndefined();
  });
  it('places a 1 length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(1);
    newGameboard.placeShip(newShip, [0, 1], 'vertical');
    newGameboard.placeShip(newShip, [2, 3], 'vertical');
    expect(newGameboard.board[0][1]).toEqual('S');
    expect(newGameboard.board[2][3]).toEqual('S');
  });
  it('places a 2 or more length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(2);
    let newShip2 = new Ship(3);
    newGameboard.placeShip(newShip, [0, 1], 'vertical');
    newGameboard.placeShip(newShip2, [5, 6], 'horizontal');
    expect(newGameboard.board[0][1]).toEqual('S');
    expect(newGameboard.board[1][1]).toEqual('S');
    expect(newGameboard.board[5][6]).toEqual('S');
    expect(newGameboard.board[5][7]).toEqual('S');
    expect(newGameboard.board[5][8]).toEqual('S');
  });
  it("doesn't create ship if ship would be outside gameboard", () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(2);
    let newShip2 = new Ship(2);
    newGameboard.placeShip(newShip, [9, 1], 'vertical');
    newGameboard.placeShip(newShip2, [1, 9], 'horizontal');
    expect(newGameboard.board[9][1]).toEqual('');
    expect(newGameboard.board[1][9]).toEqual('');
  });
  it('marks spots when placed 1 length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(1);
    newGameboard.placeShip(newShip, [5, 5], 'vertical');
    expect(newGameboard.board[5][5]).toEqual('S');
    expect(newGameboard.board[4][5]).toEqual('#');
    expect(newGameboard.board[4][4]).toEqual('#');
    expect(newGameboard.board[4][6]).toEqual('#');
    expect(newGameboard.board[5][4]).toEqual('#');
    expect(newGameboard.board[5][6]).toEqual('#');
    expect(newGameboard.board[6][5]).toEqual('#');
    expect(newGameboard.board[6][6]).toEqual('#');
    expect(newGameboard.board[6][4]).toEqual('#');
  });
  it('marks spots vertically when placed 2 length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(2);
    newGameboard.placeShip(newShip, [5, 5], 'vertical');
    expect(newGameboard.board[5][5]).toEqual('S');
    expect(newGameboard.board[6][5]).toEqual('S');
    expect(newGameboard.board[4][4]).toEqual('#');
    expect(newGameboard.board[4][5]).toEqual('#');
    expect(newGameboard.board[4][6]).toEqual('#');
    expect(newGameboard.board[5][4]).toEqual('#');
    expect(newGameboard.board[5][6]).toEqual('#');
    expect(newGameboard.board[6][6]).toEqual('#');
    expect(newGameboard.board[6][4]).toEqual('#');
    expect(newGameboard.board[7][4]).toEqual('#');
    expect(newGameboard.board[7][5]).toEqual('#');
    expect(newGameboard.board[7][6]).toEqual('#');
  });
  it('marks spot horizontally when placed 2 length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(2);
    newGameboard.placeShip(newShip, [5, 5], 'horizontal');
    expect(newGameboard.board[5][5]).toEqual('S');
    expect(newGameboard.board[5][6]).toEqual('S');
    expect(newGameboard.board[5][4]).toEqual('#');
    expect(newGameboard.board[4][4]).toEqual('#');
    expect(newGameboard.board[6][4]).toEqual('#');
    expect(newGameboard.board[4][5]).toEqual('#');
    expect(newGameboard.board[6][5]).toEqual('#');
    expect(newGameboard.board[4][6]).toEqual('#');
    expect(newGameboard.board[6][6]).toEqual('#');
    expect(newGameboard.board[4][7]).toEqual('#');
    expect(newGameboard.board[5][7]).toEqual('#');
    expect(newGameboard.board[6][7]).toEqual('#');
  });
  it('marks spot vertically when placed 3 length ship ', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(3);
    newGameboard.placeShip(newShip, [7, 0], 'vertical');
    expect(newGameboard.board[7][0]).toEqual('S');
    expect(newGameboard.board[8][0]).toEqual('S');
    expect(newGameboard.board[9][0]).toEqual('S');
    expect(newGameboard.board[6][0]).toEqual('#');
    expect(newGameboard.board[6][1]).toEqual('#');
    expect(newGameboard.board[7][1]).toEqual('#');
    expect(newGameboard.board[8][1]).toEqual('#');
    expect(newGameboard.board[9][1]).toEqual('#');
  });
  it('marks spot horizontally when placed 3 length ship', () => {
    let newGameboard = new Gameboard();
    newGameboard.init();
    let newShip = new Ship(3);
    newGameboard.placeShip(newShip, [9, 7], 'horizontal');
    expect(newGameboard.board[9][7]).toEqual('S');
    expect(newGameboard.board[9][8]).toEqual('S');
    expect(newGameboard.board[9][9]).toEqual('S');
    expect(newGameboard.board[8][6]).toEqual('#');
    expect(newGameboard.board[9][6]).toEqual('#');
    expect(newGameboard.board[8][7]).toEqual('#');
    expect(newGameboard.board[8][8]).toEqual('#');
    expect(newGameboard.board[8][9]).toEqual('#');
  });
});
